- Testing/Python/ReportingRoundTripTest.py
Need to import the logging module to use the new logging calls.
> BUG: import logging

- Py/DICOMSegmentationPlugin.py
- Util/LabelToDICOMSEGConverterScript.py
Fixing tests on the dashboard by explicitly importing os, DICOMLib
> 42 fix tests

- Py/CMakeLists.txt
- Py/SEGExporterSelfTest.py
- SEGSupport/EncodeSEG.cxx
- SEGSupport/SEG2NRRD.cxx
- notes.txt
Should be possible to manually resolve issues.
> Refactor to new dcmtk

- SEGSupport/EncodeSEG.cxx
> BUG: fix initialization of ImageOrientationPatient

- Py/DICOMSegmentationPlugin.py
- Py/SEGExporterSelfTest.py
- SEGSupport/SEG2NRRD.cxx
This matches the pull request with the same name in the Slicer trunk.
I will push the Slicer one to svn (it should be okay even if this doesn't get updated in sync).
> Integrate editor seg export

- Py/DICOMSegmentationPlugin.py
- SEGSupport/SEG2NRRD.cxx
DicomSegmentation.py
* Added code within the import functions that adds the DICOM segmentation to a segmentation object.
* Added functions: examineForExport, export, and exportAsDICOMSEG (which is a modified version of exportAsDICOMSEG from EditUtil.py in the Slicer core.
SEG2NRRD.cxx
* Changes made by Andras that prevents the CLI from crashing due to an incorrectly allocated number of Slices.
> Add support for the Segmentations Module

- Py/DICOMParametricMapPlugin.py
TODO:
- add exporter
- add units attributes, following the discussion in
https://github.com/Slicer/Slicer/pull/592
tested locally ...
> ENH: adding DICOM Parametric Map plugin

- Py/DICOMSegmentationPlugin.py
- Py/DICOMTID1500Plugin.py
- Py/Reporting.py
- partially addresses issue #85
- fixes #89 
TODO: update for exporting DICOM as well
> ENH: Updated load method of DICOMSegmentationPlugin to use dcmqi segimage2itkimage cli (issue #85)

- Py/DICOMTID1500Plugin.py
created segmentationNode referenced in measurement report for enable displaying in Reporting
> Loading TID1500 including segmentation and scalar volumes

- Py/Reporting.py
Re #99 this accounts for the API changes in the Slicer core
WIP: do not merge!
> BUG: update export code

- Py/Reporting.py
- some minor refactoring by extracting a new method and removing unused variables
fixes #90
fixes #103
fixes #106
fixes #107
fixes #110
> Enabling read only mode for reports read from SlicerDICOMDatabase

- Py/QuantitativeReporting.py
> BUG: Checking if developerMode is active for avoiding crash of setting up the UI 

- Py/CMakeLists.txt
- Py/DICOMParametricMapPlugin.py
- Py/DICOMPluginBase.py
- Py/DICOMSegmentationPlugin.py
- Py/DICOMTID1500Plugin.py
- Py/QuantitativeReporting.py
- Py/startSlicelet.sh
fixes #116 
addresses #104
@fedorov please test this. I hope that fixes the the issues regarding the missing files after restarting Slicer, even when I am not sure, why I cannot reproduce it properly.
> Cleanup temp directories, assigning initial terminology to new segments, and added slicelet

- Py/DICOMSegmentationPlugin.py
> BUG: renamed JSON attributes (issue #132)

- Py/QuantitativeReporting.py
fixes #132 
@fedorov Sorry, my mistake that i missed that.
> BUG: renamed LabelID to labelID (issue #132)

- QuantitativeReporting.py
> Fix testdata download and missing patient information due to missing signal connection

- QuantitativeReporting.py
for reference https://github.com/Slicer/Slicer/commit/37bb711bf7951ba48658a86faa0466d724d88afd
> BUG: fix renamed method in Slicer Core

- QuantitativeReporting.py
fixes #173 
depends on https://github.com/QIICR/SlicerDevelopmentToolbox/pull/17
depends on https://github.com/QIICR/SlicerDevelopmentToolbox/pull/18
> ENH: added widgets for importing from segmentation/labelmap (issue #173)

- DICOMPlugins/DICOMSegmentationPlugin.py
- QuantitativeReporting.py
fixes partially #197
* TODO: 
* add some more checks for making sure that referenced segmentation node's ReferenceImageGeometry of measurement table was not set with a non DICOM volume.
> ENH: Remove obsolete code

- DICOMPlugins/DICOMParametricMapPlugin.py
> ENH: update plugin to use node attributes for quantity/units

- QuantitativeReporting.py
* on entering module all selectors are set to None and signals are connected
* on exiting module master and segmentation volume selector signals are disconnected
* on segmentation selected, referenced master volume is checked for type DICOM
* if not DICOM a dialog is prompted to the user if new segmentation node
should be created since the referenced master volume is non DICOM
fixes #179
> BUG: handling situation when referenced master volume is non DICOM 

- DICOMPlugins/DICOMSegmentationPlugin.py
- QuantitativeReporting.py
> WIP: exporting to user selected directory and configuring availability of import area

- QuantitativeReporting.py
* moved methods to SlicerDevelopmentToolbox
depends on https://github.com/QIICR/SlicerDevelopmentToolbox/pull/19
> ENH: preparations for importing label map that has different geometry

- DICOMPlugins/DICOMSegmentationPlugin.py
- QuantitativeReporting.py
fixes #187
fixes #188 
fixes #189
fixes #191 
fixes #192
depends on https://github.com/QIICR/SlicerDevelopmentToolbox/pull/21
> ENH: splitted import area and hiding label after importing into segmentation

- DICOMPlugins/DICOMSegmentationPlugin.py
There was a cryptic runtime error in Slicer on Windows, and I thought the most
likely reason is the exceedingly long command line (the length for a whole body
CT segmentation was way way over the Windows limit of ~8k). Copying the files
into a temporary directory and using the directory parameter resolved the
issue. Temporary directory is removed after conversion is done. In the future,
we should address this by allowing to pass list of files in the JSON directly
in dcmqi (issue created https://github.com/QIICR/dcmqi/issues/297).
> BUG: copy DICOM files to a temp directory for SEG conversion

- DICOMPlugins/DICOMSegmentationPlugin.py
- QuantitativeReporting.py
> WIP: fixes wrong api calls caused by Slicer Core changes (issue #197)

- CMakeLists.txt
- DICOMPlugins/DICOMSegmentationPlugin.py
- DICOMPlugins/base/DICOMPluginBase.py
- QuantitativeReporting.py
- Testing/CMakeLists.txt
- Testing/QuantitativeReportingTests.py
> WIP: added integration tests and referencing right master volume from segmentation

- QuantitativeReporting/CMakeLists.txt
- Testing/QuantitativeReportingTests.py
> BUG: adding python source files explicitly (issue #203)

- QuantitativeReporting/QRCustomizations/CustomSegmentStatistics.py
- QuantitativeReporting/QuantitativeReporting.py
for reference to prior discussion https://github.com/QIICR/QuantitativeReporting/pull/207
> ENH: removing unneeded plugins only from instantiated SegmentStatisticsLogic

- DICOMPlugins/DICOMTID1500Plugin.py
> ENH: Disabling DICOMLongitudinalTID1500Plugin for now since the workflow

- DICOMPlugins/CMakeLists.txt
for the reference https://github.com/SBU-BMI/SlicerOpenCV/pull/43#issuecomment-362464666
> BUG: same scripts are specified multiple times causing problems

- CMakeLists.txt
- DICOMPlugins/DICOMTID1500Plugin.py
- Testing/CMakeLists.txt
> BUG: failing unittests due to missing dependencies (issue #218)

- QuantitativeReporting/QuantitativeReporting.py
for the reference: https://github.com/QIICR/SlicerDevelopmentToolbox/pull/27
> ENH: qt5 version updates

- QuantitativeReporting/CMakeLists.txt
- QuantitativeReporting/QuantitativeReporting.py
> minor changes made during NAMIC project week

- DICOMPlugins/DICOMSegmentationPlugin.py
- QuantitativeReporting/CMakeLists.txt
- QuantitativeReporting/QRCustomizations/SegmentEditorAlgorithmTracker.py
- QuantitativeReporting/QuantitativeReporting.py
ENH: functionality to specify DICOM algorithm name and type and export to DICOM SEG
> Algorithm tracking

- DICOMPlugins/DICOMTID1500Plugin.py
Installing the extension led to the following error messages.
So this change only gets the references to other plugins when needed, which
happens after the full application has started up.
[DEBUG][Qt] 21.08.2018 10:07:11 [] (unknown:0) - Session start time .......: 2018-08-21 10:07:11
[DEBUG][Qt] 21.08.2018 10:07:11 [] (unknown:0) - Slicer version ...........: 4.9.0-2018-08-17 (revision 27353) macosx-amd64 - installed release
[DEBUG][Qt] 21.08.2018 10:07:11 [] (unknown:0) - Operating system .........: Mac OS X / 10.13.6 / 17G65 - 64-bit
[DEBUG][Qt] 21.08.2018 10:07:11 [] (unknown:0) - Memory ...................: 65536 MB physical, 5120 MB virtual
[DEBUG][Qt] 21.08.2018 10:07:11 [] (unknown:0) - CPU ......................: GenuineIntel Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz, 12 cores, …
> BUG: don't rely on plugin discovery order

- DICOMPlugins/DICOMParametricMapPlugin.py
- DICOMPlugins/DICOMSegmentationPlugin.py
- QuantitativeReporting/QRCustomizations/CustomDICOMDetailsWidget.py
- QuantitativeReporting/QRCustomizations/CustomSegmentEditor.py
- QuantitativeReporting/QRCustomizations/CustomSegmentStatistics.py
- QuantitativeReporting/QRCustomizations/SegmentEditorAlgorithmTracker.py
- QuantitativeReporting/QRUtils/htmlReport.py
- QuantitativeReporting/QRUtils/testdata.py
- QuantitativeReporting/QuantitativeReporting.py
- Testing/QuantitativeReportingTests.py
depends on https://github.com/QIICR/SlicerDevelopmentToolbox/pull/36
> ENH: updates to make module work with python 3

- DICOMPlugins/DICOMSegmentationPlugin.py
> BUG: fix SH SEG export regression

- DICOMPlugins/DICOMSegmentationPlugin.py
> BUG: fix SEG SH export

- QuantitativeReporting/QRCustomizations/CustomSegmentEditor.py
- QuantitativeReporting/QuantitativeReporting.py
- Testing/QuantitativeReportingTests.py
* fixed self tests related to changes in Slicer's API
* in python3 exceptions no longer have a message attribute
> COMP: updated code and self test

- DICOMPlugins/DICOMSegmentationPlugin.py
[#398](https://github.com/QIICR/dcmqi/issues/398) - All SRT codes were replaced by their corresponding SCT codes.
> SRT codes were replaced with SCT

- DICOMPlugins/DICOMSegmentationPlugin.py
Problems fixed:
- Segment description or code meaning was used instead of segment label.
- When the same label was used multiple times, _1, _2, ... suffixes were added (because segment name was passed via node name).
Fixes #251
> Fix setting of segment name in when loading segmentation from DICOM

- DICOMPlugins/DICOMParametricMapPlugin.py
- DICOMPlugins/DICOMTID1500Plugin.py
TID1500 and Parametric mapping plugins are updated to work with latest Slicer-4.11 version.
> Fix tid1500 plugin

- Testing/QuantitativeReportingTests.py
> BUG: initialize user name when testing

- DICOMPlugins/DICOMSegmentationPlugin.py
Display more specific messages to help the user figure out what to do (e.g., have the referenced image in the DICOM database).
> Improve error reporting during DICOM Segmentation object export

- DICOMPlugins/DICOMSegmentationPlugin.py
https://github.com/Slicer/Slicer/commit/65409219f724bf03bd0307e9c2062c06030f3951
> Update DICOMSegmentationPlugin.py for change in name of context
