- Py/DICOMSegmentationPlugin.py
Go back to importing the plugin and laodable from the DICOMLib.
Update syntax for using DICOM loadable.
Issue #48
> BUG: update plugin to work with new python namespaces

- Logic/vtkSlicerReportingModuleLogic.cxx
The logic C++ class was trying to access the LabelStatistics
module via python, but for the self test to pass on the dashboard
it needs to import the module and access it via
LabelStatistics.LabelStatisticsLogic
> BUG: fix python namespace issue in Reporting test

- Logic/vtkSlicerReportingModuleLogic.cxx
This commit fixes the following warnings:
/home/jcfr/Projects/Reporting/Logic/vtkSlicerReportingModuleLogic.cxx: In member function ‘std::string vtkSlicerReportingModuleLogic::DicomSegWrite(vtkCollection*, std::string, bool)’:
/home/jcfr/Projects/Reporting/Logic/vtkSlicerReportingModuleLogic.cxx:2182:41: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
for(int i=0;i<dcmDatasetVector.size();i++){
^
/home/jcfr/Projects/Reporting/Logic/vtkSlicerReportingModuleLogic.cxx:2197:41: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
for(int i=0;i<dcmDatasetVector.size();i++){
^
/home/jcfr/Projects/Reporting/Logic/vtkSlicerReportingModuleLogic.cxx:1862:21: warning: variable ‘colorNode’ set but not used …
> STYLE: Fix compilation warnings

- Util/LabelToDICOMSEGConverter/Testing/Python/LabelToDICOMSEGConverterSelfTest.py
The test was getting all the scalar volumes and checking for the
label attribute, but the change to use a new class, vtkMRMLLabelMapVolumeNode,
meant that the sought after label file was not being found to check.
This change updates the test to get just the label maps in the scene and
to test that there is one and it is correct.
> BUG: update test to use new label map class

- Logic/vtkSlicerReportingModuleLogic.cxx
- Logic/vtkSlicerReportingModuleLogic.h
- Py/DICOMSegmentationPlugin.py
When reading in a DICOM segmentatin file, create one color table node
for all the segments, and build up a terminology associated with the
segmentation from the .info files.
Adjusted the logic call to not use the color node, do the terminology and color
information file parsing in the segmentation plugin.
Added a check that the SEG2NRRD CLI was loaded to prevent a crash if Slicer was started up
without CLI modules.
Issue #52
> ENH: add color table and terminology for DICOM segmentation reading

- Py/DICOMSegmentationPlugin.py
- SEGSupport/SEG2NRRD.cxx
After updates to the Slicer topic branch in naucoin
4047-Add-semantic-color-information-to-color-selector-in-editor
parse out and set the region information read from the segmentation object. Take
into account that the modifier lines may be omitted in the .info file, refer
to SEG2NRRD for the calls that do the writing.
Updated SEG2NRRD to set the label map pixel values to the segmentation number
rather than always using 1. This allows the colors to display properly with one
color node rather than having to define a color node per segmentation.
Issue #52
> ENH: Add terminology region support, fix color display

- Py/DICOMSegmentationPlugin.py
When parsing the .info files that come with segmentation label
images, some terminology information may be missing. This change
sets some default values.
See issue #52 and the comment to #57
> ENH: set default terminology terms

- SEGSupport/EncodeSEG.cxx
RGB is arguably more common color scheme than CIELab, and the one used in Slicer.
Conversion functions used are the same as in SEG2NRRD (this also makes the process
symmetric, since SEG2NRRD outputs RGB colors).
In the future, it is suggested that the conversion routines move somewhere else
to be more accessible, perhaps DCMTK is the best place for this.
This should resolve #62.
> ENH: accept RGB display value in place of CIELab

- Py/DICOMSegmentationPlugin.py
- Py/SEGExporterSelfTest.py
- SEGSupport/SEG2NRRD.cxx
Update the plugin to use the new order of terms when adding a term to
a terminology.
Update the SEG exporter self test to use the new color logic methods,
Depends on Nov 12/15 update to:
https://github.com/naucoin/Slicer/tree/4047-Add-semantic-color-information-to-color-selector-in-editor
Unify terminology file formats:
Update SEG2NRRD.cxx to use the format from EncodeSEG.cxx.
Update DICOMSegmentationPlugin.py to parse the single line
format, with the capability to deal with multiple lines defining
terminology for different labels in one file.
Issue #52
> ENH: update to use new terminology methods, order

- Py/DICOMSegmentationPlugin.py
Enclose trying to access the seg2nrrd module in a try block,
otherwise the loading process will hang if the CLI module wasn't
loaded correctly.
> BUG: Fix the loaded check for seg2nrrd

- CMakeLists.txt
- Py/CMakeLists.txt
- Py/DICOMSegmentationPlugin.py
- Py/DICOMTID1500Plugin.py
- Py/Reporting.py
- Py/SEGExporterSelfTest.py
for the reference #74
depends on https://github.com/SlicerProstate/SlicerProstate/pull/38
depends on https://github.com/QIICR/dcmqi/pull/107
@fedorov work in progress
> New reporting module prototype

- Py/DICOMParametricMapPlugin.py
Re #127
Store quantity and units for parametric maps as stringified JSON dictionaries in
DICOM.QuantityValueCode and DICOM.MeasurementUnitsCode.
@pieper @lassoan - can you take a look and let me know what you think about this?
When we agree on the approach, I would like to add similar functionality to the other DICOM plugins (where it makes sense) that load image volumes. It is not always as straightforward as with parametric maps, but when it is not possible to figure out these items, we can just leave those attributes uninitialized. When they are initialized, they would be used by the segment statistics module plugins, and should be useful for other purposes down the road.
> ENH: store quantity and units of the volume

- CMakeLists.txt
- Py/DICOMTID1500Plugin.py
re #120
When measurements SR references a RWVM instance, check whether the series instance
UID referenced by SEG is the same as the one referenced by RWVM. If yes, use RWVM
plugin to load the scaled series.
This does not add support for saving segmentation of volumes loaded from RWVM.
> ENH: account for the referenced RWVM instance

- QuantitativeReporting.py
* now using DICOM.instanceUIDs instead.
depends on QIICR/SlicerDevelopmentToolbox/pull/9
> BUG: watchbox could not get populate due to missing storageNode

- DICOMPlugins/DICOMTID1500Plugin.py
- QuantitativeReporting.py
fixes #168
* segmentStatisticsConfigButton added for configuring SegmentStatistics
calculators
* TODO: this should be moved somewhere else since in FourUp
Quanitative the Measurements area disappears from main module
widget
* for now just catching the exception and printing a message
* all quantities/units for which we don't have the code sequence
definitions yet, won't be added to the output DICOM
* TODO: add code sequences for handling quantities/units other than
the currently supported ones only
We can merge this once the new SegmentStatistics additions has been merged to Slicer core
> ENH: integration of SegmentStatistics (issue #168, #161)

- QuantitativeReporting/QRCustomizations/CustomSegmentStatistics.py
The reason for removing that plugin from the plugins list is that Measurements were duplicated.
I implemented it the way it's done in the SegmentStatisticsTest [1] although I don't think that it should be implemented that way because it "unregisters" the SegmentStatistics plugins globally since it's set on the SegmentStatisticsLogic class directly. 
Calling SegmentStatistics module afterwards, it only those plugins, that I registered for QuantitativeReporting are displayed, but all others are gone.
[1] https://github.com/Slicer/Slicer/blob/08fec03c10955e813b22886697ee2cdb346898df/Modules/Scripted/SegmentStatistics/SegmentStatistics.py#L829-L832
cc @chribaue
> ENH: removed LabelmapSegmentStatisticsPlugin from custom statistics

- Testing/CMakeLists.txt
with slicer_add_python_unittest and making tests available in module
selector via slicerMacroBuildScriptedModule
is supposed to fix #203
> BUG: replaced obsolete ctkMacroCompilePythonScript (issue #203)

- CMakeLists.txt
- QuantitativeReporting/QuantitativeReporting.py
- Testing/CMakeLists.txt
- Testing/QuantitativeReportingTests.py
for the reference #221 
will close the issue, if tests are succeeding 
@cpinter I knot that you had issues in #218 but I would like to have the tests as a separate module as long as Testing is enabled during the build. If you have a better idea, let me know. For now, I will merge this PR and see what the dashboard reports regarding the tests.
> BUG: fix failing tests (issue #221)

- DICOMPlugins/DICOMSegmentationPlugin.py
- DICOMPlugins/DICOMTID1500Plugin.py
DICOMSegmentationPlugin did not report any error when the conversion failed (it raised an exception, but the Python wrapper ignores exceptions).
Also fixed capturing of the exception message: in Python3, exception does not have message attribute anymore.
> BUG: Fix error reporting in segmentation and TID1500 plugins

- DICOMPlugins/DICOMSegmentationPlugin.py
If SeriesDescription has not been specified yet then use the node's name as default (node name is set from series description during DICOM import).
Export series with the specified SeriesNumber (previously, the exported series number was always 100).
> ENH: Improve segmentation export custom tags

- CMakeLists.txt
Since the "<extension_name>Config.cmake" module is not available when
bundling extension sources, this commit excludes the corresponding
requirements.
It also skips the setting of DEPENDENCIES_ADDITIONAL_MODULE_PATHS
because modules associated with the SlicerDevelopmentToolbox, DCMQI
and PETDICOMExtension extensions are built along side the QuantitativeReporting
ones.
> COMP: Support bundling in custom application

- DICOMPlugins/DICOMSegmentationPlugin.py
By default `slicer.util.tempDirectory()` already contains the current timestamp - the additional subdirectory `self.currentDateTime` in `self.tempdir` leaves you over time with a collection of empty `slicer.util.tempDirectory()` (cf. image). Despite they are in a temp directory, I think it is avoidable ;-)
> Fixes deletion of nested tempdir

- DICOMPlugins/DICOMM3DPlugin.py
- DICOMPlugins/DICOMSegmentationPlugin.py
This commit replaces SetMasterRepresentationName (deprecated) by the new SetSourceRepresentationName in response to the following warning when using the module.
```
[VTK] Warning: In vtkSegmentation.h, line 511
[VTK] vtkSegmentation (0x45d028c0): vtkSegmentation::SetMasterRepresentationName() method is deprecated, please use SetSourceRepresentationName method instead
```
> ENH: Replace deprecated SetMasterRepresentationName

- DICOMPlugins/DICOMSegmentationPlugin.py
Slicer 5.8.1 stable does not have the backward compatible API, breaking DICOM SEG load
Re https://github.com/Slicer/Slicer/issues/8324 #282
@lenagiebeler this should fix the issue you identified! Thank you for bringing this up.
> BUG: fall back to deprecated method

- DICOMPlugins/DICOMSegmentationPlugin.py
- QuantitativeReporting/QRCustomizations/CustomSegmentStatistics.py
- QuantitativeReporting/QRUtils/htmlReport.py
fixes #285
I'll also add deprecated backward-compatibility methods to Slicer core to avoid potential errors like these elsewhere.
> BUG: Update Terminologies API to work with both latest and older Slicer versions

- DICOMPlugins/DICOMM3DPlugin.py
- DICOMPlugins/DICOMTID1500Plugin.py
- DICOMPlugins/base/DICOMPluginBase.py
Replace deprecated function `pydicom.read_file()` by `pydicom.dcmread()`, cf.:
https://github.com/pydicom/pydicom/pull/506
The extension is currently not functional with preview version 3DSlicer 5.9, since in there python 3.11 will install `pydicom>=3.0` by default. This PR fixes this issue.
> Replace deprecated pydicom function
